---
- name: "OpenFaaS deployment"
  block:
    - name: "Check if OpenFaaS is already deployed"
      shell: helm list | grep openfaas
      register: deploy_openfaas
      failed_when: deploy_openfaas.rc != 0 and deploy_openfaas.rc != 1

    - name: "Deploy OpenFaaS"
      include_tasks: openfaas.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: deploy_openfaas.rc == 1

  when: faas_framework == 'openfaas'

- name: "Knative deployment"
  block:
    - name: "Check if Knative Operator is already deployed"
      shell: kubectl get deployment knative-operator
      register: deploy_knative
      failed_when: deploy_knative.rc != 0 and deploy_knative.rc != 1

    - name: "Deploy Knative"
      include_tasks: knative.yaml
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"
      when: deploy_knative.rc == 1

  when: faas_framework == 'knative'