---
- name: "Create OpenFaas namespaces"
  command: kubectl apply -f https://raw.githubusercontent.com/openfaas/faas-netes/master/namespaces.yml

- name: "Wait for tiller-deploy ready status"
  command: kubectl rollout status deployment/tiller-deploy -n kube-system

- name: "Generate password for the gateway"
  set_fact:
    gw_password: "{{ lookup('password', '/var/tmp/gw_password chars=ascii_lowercase,digits length=40') }}"
  when: gw_password is undefined

- name: "Create secrets to enable basic auth"
  command: >
    kubectl -n openfaas create secret generic basic-auth
    --from-literal=basic-auth-user=admin
    --from-literal=basic-auth-password={{ gw_password }}

- name: "Add OpenFaaS helm chart"
  command: helm repo add openfaas https://openfaas.github.io/faas-netes/

- name: "Update helm repositories"
  command: helm repo update

- name: "Deploy OpenFaaS in Master using helm"
  command: >
    helm upgrade openfaas --install openfaas/openfaas {{ '' if faas_chart_version == 'latest' else ('--version ' + faas_chart_version) }}
    --namespace openfaas
    --set basic_auth=true
    --set functionNamespace=openfaas-fn
    --set faasIdler.dryRun=false
    --set faasIdler.inactivityDuration=1m
    --set queueWorker.ackWait={{ ack_wait }}s
    --set tolerations[0].key=node-role.kubernetes.io/master
    --set tolerations[0].operator=Exists
    --set tolerations[0].effect=NoSchedule
  when: master_deploy == true

- name: "Deploy OpenFaaS in WN using helm"
  command: >
    helm upgrade openfaas --install openfaas/openfaas {{ '' if faas_chart_version == 'latest' else ('--version ' + faas_chart_version) }}
    --namespace openfaas
    --set basic_auth=true
    --set functionNamespace=openfaas-fn
    --set faasIdler.dryRun=false
    --set faasIdler.inactivityDuration=1m
    --set queueWorker.ackWait={{ ack_wait }}s
  when: master_deploy == false

- name: "Download the CLI binary"
  get_url:
    url: https://github.com/openfaas/faas-cli/releases/download/{{ cli_version }}/faas-cli 
    dest: /usr/local/bin/faas-cli
    mode: 0755

- name: "Create 'faas' symlink"
  command: ln -sf /usr/local/bin/faas-cli /usr/local/bin/faas
  
- name: "Add OpenFaas URL to FaasCli"
  lineinfile: 
    path: /etc/environment
    line: OPENFAAS_URL=127.0.0.1:31112

- name: "OSCAR Worker deployment"
  block:

    - name: "Delete OpenFaaS nats-queue-worker deployment"
      command: kubectl delete deployment queue-worker -n openfaas

    - name: "Create OSCAR namespaces"
      command: kubectl apply -f https://raw.githubusercontent.com/grycap/oscar-worker/master/yaml/oscar-worker-namespaces.yaml

    - name: "Apply oscar-worker-rbac.yaml"
      command: kubectl apply -f https://raw.githubusercontent.com/grycap/oscar-worker/master/yaml/oscar-worker-rbac.yaml

    - name: "Create a copy of gateway secret in oscar namespace"
      command: >
        kubectl -n oscar create secret generic basic-auth
        --from-literal=basic-auth-user=admin
        --from-literal=basic-auth-password={{ gw_password }}

    - name: "Deploy OSCAR Worker"
      block:
        - template: src=oscar-worker-dep.j2 dest=/tmp/oscar-worker-dep.yaml
        - command: kubectl apply -f /tmp/oscar-worker-dep.yaml

  when: deploy_oscar_worker == true
