---
- name: Clone OpenFaas repo
  git:
    repo: 'https://github.com/openfaas/faas-netes'
    dest: /tmp/faas-netes
    version: "{{ faas_version }}"
    force: yes

- name: "Create OpenFaas namespaces"
  command: kubectl apply -f namespaces.yml
  args:
    chdir: /tmp/faas-netes

- name: "Set queue worker ack wait"
  template: src=queueworker-dep.j2 dest=/tmp/faas-netes/yaml/queueworker-dep.yml

- name: "Deploy all OpenFaaS components"
  command: kubectl apply -f ./yaml
  args:
    chdir: /tmp/faas-netes

- name: "Download the CLI binary"
  get_url:
    url: https://github.com/openfaas/faas-cli/releases/download/{{ cli_version }}/faas-cli 
    dest: /usr/local/bin/faas-cli
    mode: 0755

- name: "Create 'faas' symlink"
  command: ln -sf /usr/local/bin/faas-cli /usr/local/bin/faas
  
- name: "Add OpenFaas URL to FaasCli"
  lineinfile: 
    path: /etc/environment
    line: OPENFAAS_URL=127.0.0.1:31112
