---
- name: Create OpenFaas namespaces
  block:
  - template:
      src: openfaas-ns.j2
      dest: /tmp/openfaas-ns.yaml
  - command: kubectl apply -f /tmp/openfaas-ns.yaml

- name: Generate password for the gateway
  set_fact:
    gw_password: "{{ lookup('password', '/var/tmp/gw_password chars=ascii_lowercase,digits length=40') }}"
  when: gw_password is undefined

- name: Check if basic auth secrets are created
  command: kubectl get secret basic-auth -n openfaas
  register: openfaas_secret_created
  failed_when: openfaas_secret_created.rc != 0 and openfaas_secret_created.rc != 1
  ignore_errors: yes
  changed_when: false

- name: Create secrets to enable basic auth
  command: >
    kubectl -n openfaas create secret generic basic-auth
    --from-literal=basic-auth-user=admin
    --from-literal=basic-auth-password={{ gw_password }}
  when: openfaas_secret_created.rc == 1

- name: Add OpenFaaS helm chart
  command: helm repo add openfaas https://openfaas.github.io/faas-netes/

- name: Update helm repositories
  command: helm repo update

- name: Create values file
  template:
    src: openfaas-values.j2
    dest: /tmp/openfaas-values.yaml

- name: Deploy OpenFaaS in WN using helm
  command: >
    helm upgrade openfaas --install openfaas/openfaas {{ '' if openfaas_chart_version == 'latest' else ('--version ' + openfaas_chart_version) }}
    --namespace openfaas
    --values /tmp/openfaas-values.yaml

- name: Download the CLI binary
  block:
  - block:
    - uri:
        url: https://api.github.com/repos/openfaas/faas-cli/releases/latest
        return_content: true
      register: json_response
    - get_url:
        url: https://github.com/openfaas/faas-cli/releases/download/{{ json_response.json.tag_name }}/faas-cli 
        dest: /usr/local/bin/faas-cli
        mode: 0755
    when: openfaas_cli_version == 'latest'
  - get_url:
      url: https://github.com/openfaas/faas-cli/releases/download/{{ openfaas_cli_version }}/faas-cli 
      dest: /usr/local/bin/faas-cli
      mode: 0755
    when: openfaas_cli_version != 'latest'

- name: Create 'faas' symlink
  command: ln -sf /usr/local/bin/faas-cli /usr/local/bin/faas
  
- name: Add OpenFaas URL to FaasCli
  block:
  - command: kubectl get svc gateway -n openfaas -o json
    register: svc
  - set_fact:
      svc_json: "{{ svc.stdout | from_json }}"
  - lineinfile: 
      path: /etc/environment
      line: OPENFAAS_URL={{ svc_json.spec.clusterIP }}:8080

